#!/bin/bash
set -e

DENO_VERSION='v1.13.2'
ALEPH_VERSION='0.3.0-beta.12'
export PATH=/vercel/.deno/bin:$PATH

curl -fsSL https://deno.land/x/install/install.sh | sh -s $DENO_VERSION
deno install --unstable -A -f -n aleph https://deno.land/x/aleph@v$ALEPH_VERSION/cli.ts
deno run -A https://deno.land/x/aleph/install.ts
aleph build
